name: MobBlockCore
version: '${project.version}'
main: me.ghostplugins.core.MobBlockCore
api-version: 1.17
authors: [ GhostPlugins ]
commands:
  arena:
    description: 'Main arena command'
    usage: /arena <idk>
